#!/bin/bash
# 
#
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

#
# On remet les polices par défaut pour la table NAT
#
iptables -t nat -P PREROUTING ACCEPT
iptables -t nat -P POSTROUTING ACCEPT
iptables -t nat -P OUTPUT ACCEPT

#
# On vide (flush) toutes les règles existantes
#
iptables -F
iptables -t nat -F

#
# Et enfin, on efface toutes les chaînes qui ne
# sont pas à defaut dans la table filter et nat

iptables -X
iptables -t nat -X

# La configuration proprement dite :


# Activer le forwarding de paquets dans le kernel :
echo 1 > /proc/sys/net/ipv4/ip_forward

# Au départ, on commence par donner la politique de base (policy) :

# iptables -P INPUT DROP
# iptables -P OUTPUT DROP
# iptables -P FORWARD DROP

# On dialogue librement avec son interface de loopback :

iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# On accepte les Pings :

iptables -A INPUT -p icmp -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT


# commande magique :

iptables -A INPUT -i vmbr0 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -o vmbr0 -m state --state NEW,ESTABLISHED -j ACCEPT

iptables -A INPUT -i vmbr1 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -o vmbr1 -m state --state NEW,ESTABLISHED -j ACCEPT

# Autoriser ssh depuis l'extérieur :
iptables -A INPUT -i vmbr0 -p tcp -s 192.168.20.0/24 --dport 22 -j ACCEPT
iptables -A OUTPUT -o vmbr0 -p tcp -d 192.168.20.0/24 --sport 22 -j ACCEPT

# Autoriser le port 8006 depuis l'extérieur :
iptables -A INPUT -i vmbr0 -p tcp -s 192.168.20.0/24 --dport 8006 -j ACCEPT
iptables -A OUTPUT -o vmbr0 -p tcp -d 192.168.20.0/24 --sport 8006 -j ACCEPT

# NAT : 

# D'abord on accepte de forwarder :

iptables -A FORWARD -i vmbr1 -o vmbr0 -j ACCEPT
iptables -A FORWARD -i vmbr0 -o  vmbr1 -m state --state RELATED,ESTABLISHED -j ACCEPT

# Le NAT proprement dit :

iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o vmbr0 -j MASQUERADE

# PAT :

iptables -t nat -A PREROUTING -p tcp -d 192.168.20.210 --dport 80 -j DNAT --to 10.8.0.254:80
iptables -t nat -A PREROUTING -p tcp -d 192.168.20.211 --dport 80 -j DNAT --to 10.8.0.9:9000
iptables -t nat -A PREROUTING -p tcp -d 192.168.20.212 --dport 80 -j DNAT --to 10.8.0.9:80
